export const DJINNI_CATEGORIES = [
  "2D Animation",
  "2D Artist",
  "3D Animation",
  "3D Artist",
  "Accountant",
  "Account Manager",
  "Advertising",
  "Affiliate Manager",
  "Android",
  "Angular",
  "Architect",
  "Artist",
  "ASP.NET",
  "Blazor",
  "Business Analyst",
  "Business Development",
  "C++",
  "CBDO",
  "CCO",
  "CEO",
  "CFO",
  "CIO",
  "C Lang",
  "CMO",
  "Content Design",
  "Content Manager",
  "Content Marketing",
  "Content Writing",
  "COO",
  "CPO",
  "CPP",
  "Creative and Gaming",
  "CSO",
  "CTO",
  "Data Analyst",
  "Data Analytics",
  "Data Engineer",
  "Data Science",
  "Delivery Manager",
  "Design",
  "Development",
  "DevOps",
  "Digital Marketing",
  "Digital Marketing Manager",
  "Dotnet Cloud",
  "Dotnet Desktop",
  "Dotnet Mobile",
  "Dotnet Web",
  "Drupal",
  "Elixir",
  "Embedded",
  "Engineering / CAD Design",
  "Engineering Manager",
  "ERP",
  "Finance Manager",
  "Finances",
  "Financial Analyst",
  "FinOps",
  "Flutter",
  "Fullstack",
  "Game Design",
  "Game Developer",
  "Golang",
  "Graphic Design",
  "Head Chief",
  "HR",
  "Illustrator",
  "Information Security",
  "Interviewer",
  "iOS",
  "Java",
  "JavaScript",
  "Kotlin",
  "Laravel",
  "Lead",
  "Leadership",
  "Lead Generation",
  "Level Design",
  "Magento",
  "Management",
  "Marketing",
  "Marketing Analyst",
  "Marketing and Sales",
  "Markup",
  "MAUI",
  "Media Buying",
  "ML AI",
  "Motion Design",
  "MS Dynamics",
  ".NET",
  ".NET Gamedev",
  "No Code",
  "Node.js",
  "Odoo",
  "Operations",
  "Other",
  "Other non-tech",
  "Other tech",
  "Penetration Tester",
  "Performance Marketing",
  "PHP",
  "PPC",
  "PR Manager",
  "Product Design",
  "Product Manager",
  "Product Owner",
  "Project Manager",
  "Python",
  "QA",
  "QA Automation",
  "Quality Assurance",
  "React.js",
  "React Native",
  "Recruiter",
  "Ruby",
  "Rust",
  "Sales",
  "Salesforce",
  "Sales Leadership",
  "Sales Manager",
  "SAP",
  "Scala",
  "Scrum Master",
  "Security",
  "Security Analyst",
  "SEO",
  "Social Media",
  "SQL",
  "Support",
  "Svelte",
  "Symfony",
  "Sysadmin",
  "Talent Acquisition",
  "Technical Writing",
  "UI UX",
  "Unity",
  "Unity Developer",
  "Unreal Developer",
  "UX Research",
  "VFX Artist",
  "Video Editor",
  "Vue.js",
  "Web Analyst",
  "WinForms",
  "WordPress",
  "WPF",
  "Xamarin",
  "Yii"
] as const

export const EXP_LEVELS = [
  { id: "no_exp", label: "Без досвіду" },
  { id: "1y", label: "1 рік" },
  { id: "2y", label: "2 роки" },
  { id: "3y", label: "3 роки" },
  { id: "4y", label: "4 роки" },
  { id: "5y", label: "5 років" },
  { id: "6y", label: "6 років" },
  { id: "7y", label: "7 років" },
  { id: "8y", label: "8 років" },
  { id: "9y", label: "9 років" },
  { id: "10y", label: "10 років" }
] as const

export type ExpLevelId = (typeof EXP_LEVELS)[number]["id"]

export const ALL_CATEGORIES_VALUE = "__ALL__"
export const ALL_CATEGORIES_LABEL = "Всі категорії"

export const CATEGORY_PAGE_SIZE = 10
